#!/bin/csh
# Create a clean GIT workarea to use for the tracking regressions

#setenv MY_REGRESSION_AREA $CEP_INSTALL/testSuites/tracking/regression

#setenv MY_REGRESSION $CEP_INSTALL/testSuites/tracking

# Want to start with a clean tree, delete it if it exists
if (-d $MY_REGRESSION_AREA) then
   echo "Tracking Directory Exists.  Deleting..."
   rm -rf $MY_REGRESSION_AREA
endif

if (-d $MY_REGRESSION_AREA) then
  echo "Tracking Directory deletion failed.  Exiting!"
  exit 1
endif


cd $MY_REGRESSION
mkdir regression

if (-d $MY_REGRESSION_AREA) then 
  echo "Clean Tracking Directory Created!"
  exit 0
else 
  echo "Tracking directory creation failed!"
  exit 2
endif
