#!/bin/csh
# This script runs a tracking regression,
# then takes a snapshot in vManager,
# and finally assigns dashboard attributes for the session.
# Everything passed is assumed relative to $RF_TOP
# An "NA" value for Jira Component says it's not applicable.

echo "Automated Tracking Regression..."

if ($#argv != 5) then
  echo "Incorrect number of arguments passed."
  echo "  block, VSIF, owner, Manual Status, Jira Component"
  exit 1
else 
  set block   = $argv[1]
  set vsif    = $argv[2]
  set owner   = $argv[3]
  set m_sts   = $argv[4]
  set jira_c  = "$argv[5]"
  echo "Running on $block"
  echo "  VSIF             = $vsif"
  echo "  Manual Status    = $m_sts"
  echo "  Owner            = $owner"
  echo "  Jira Comp        = $jira_c"
endif


#Necessary Environment Variables
setenv VSIF_TOP $CEP_INSTALL/vmanager/vsif
source $CEP_INSTALL/vmanager/scripts/tracking_environment_setup.csh
setenv VMGR_SERVER 566195-mitll:8810

# Change into the TB directory
cd $MY_REGRESSION_AREA

  echo "  CEP_INSTALL                 = $CEP_INSTALL"
  echo "  REGRESSION_AREA             = $MY_REGRESSION_AREA"
  echo "  VPLAN_AREA                  = $VPLAN_TOP"
  echo "  vManager Server             = $VMGR_SERVER"
  echo "  PATH Version                = $PATH"

# Assign the full paths
set vsif    = ${VSIF_TOP}/${vsif}
set m_sts   = ${VPLAN_TOP}/${m_sts}

# Grab a date string 
set tracking_date = `date +%Y_%m_%d`

# Run the regression, and wait for completion,
# don't send e-mail.
# Then grab the runVmanager return code which 
# contains the number of failed tests.
#runVmanager -t $vm_list -wfcdn | tee ${block}_run_vm.log
vmanager -server $VMGR_SERVER -execcmd "launch -wait ${vsif}" |& tee ${block}_vm.log
#vmanager -server $VMGR_SERVER -execcmd "launch -wait ${vsif}" |& tee ${block}_vm.log
#vmanager -server sjcvl-vmgr-cep:8810 -execcmd "launch -wait ${vsif}" |& tee ${block}_vm.log
set vm_rc = $?

# Prep a log file that is in the format vm_snapshot wants to see.
set session_name=`cat ${block}_vm.log | sed -n -e 's/*I,runner.sessionStarted: Session \(.*\) started./\1/p'`
echo "Session ${session_name} status is completed"  >> ${block}_run_vm.log
 
# Snapshot the session and assign to the block owner
if ("$jira_c" != "NA") then
  $VM_DASHBOARD/contrib/vm_snapshot.pl -l ${block}_run_vm.log -o $owner -b $block -c $block -s $m_sts --date_string $tracking_date -j "$jira_c"
  set ss_rc = $?
else 
  $VM_DASHBOARD/contrib/vm_snapshot.pl -l ${block}_run_vm.log -o $owner -b $block -c Test -s $m_sts --date_string $tracking_date --debug 1
  set ss_rc = $?
endif

exit 0
